### PR TITLE
Add return home btn

### LINKED ISSUE #10: Add a "go to home" button
Hello Contributors, I want someone to add a go to home button which enables user to go to landing page while playing the game.

### PR DESCRIPTION
**Pull request by Owen-Dechow**
closes #10
Implements a simple return home button using only HTML & CSS.

### CODE REVIEW

**Review by arpittyagi102 — COMMENTED** [review]
Hello, Thank you for contributing
the return home button is pretty basic, make it attractive as standard
> tip : you may add a image with return symbol

Also the return home button is not visible is Hard mode
> though i like the translate rotate effect on hover

**Comment by Owen-Dechow** [comment]
Hello, thank you for taking the time to look at my contribution. I opted for a font improvement over using an image to maintain accessibility. You also mentioned not being able to see it from the hard mode. Unfortunately this is a slightly harder fix as the page itself isn't yet completely responsive. You can still access the button by scrolling down on the page but I can't make it visible until the game is fully responsive (sorry).

May I also suggest moving you preexisting image text to a font family instead. It is considered a bad practice to have images as text (this is just a suggestion, if you raise a problem I'd be happy to help).

Finally I won't be able to make any changes to my pull request for the remainder of the week (sorry) but, if you have any concerns questions or more, I'll get back as soon as possible.

**Comment by Owen-Dechow** [comment]
Thank you for your suggestions. I can't implement everything you wanted
but, I did what I can. I left a comment on the pull request with more
information.

**Review by arpittyagi102 — COMMENTED** [review]
Okay just increase the font size of the "return home" button and move it to top-right

**Comment by Owen-Dechow** [comment]
I increased the font size but I won't be able the adjust it's placement because I'm working from a phone at the moment.
I did look to see how best to move it to the top right but there's no practical way to do so without ruining the responsiveness.
I can make these changes but they'll take time and I won't be able to get started on them until the end of this week. (Although In my opinion it is better to leave the return home button on the bottom)

**Comment by arpittyagi102** [comment]
Okay @Owen-Dechow, I am merging this PR
Please give this repository a star 🌟

**Review by arpittyagi102 — APPROVED** [review]
Okay @Owen-Dechow, I am merging this PR
Please give this repository a star 🌟

**Pull request merged**
