### PR TITLE
Improving website performance by .webp

### PR DESCRIPTION
**Pull request by eKeiran**
Changed all the .png to .webp

### CODE REVIEW

**Review by arpittyagi102 — COMMENTED** [review]
Hey, thank you so much !
btw can you solve the problem of loading of the images after being called ?
for example lets say when we first click at the box to show the gift then it loads the images which takes a bit time but once loaded when we click on other gifts it doesn't take anytime, as they are already loaded by the browser.
can you do something like on window load its already loads the gift or bomb images ?
i hope i am clear...

**Comment by eKeiran** [comment]
Sure! I can preload the images using JS so it no longer takes time for them to load. I'll commit that soon.

**Comment by eKeiran** [comment]
Hey @arpittyagirocks the gift images load faster now but the other images such as the background, moves and restart are still slow so I think I'll add them to be preloaded as well and see how it works after

**Review by arpittyagi102 — APPROVED** [review]
This is amazing! Thank you for your contribution 
Please give this repository a star

**Pull request merged**
